# Site settings
name: Name Here
title: Name Here | Position
description: A former engineering student.
url: http://github.com
baseurl: "/mclaughlinryan.github.io"
email: email@gmail.com
#cover: http://brittanychiang.com/v2/img/og.jpg
#logo: http://brittanychiang.com/v2/img/logo-black.png
#resume: http://brittanychiang.com/v2/resume.pdf
social:
  - title: email
    url: mailto:email@gmail.com
  - title: twitter
    url: https://twitter.com/
  - title: instagram
    url: https://instagram.com/
  - title: codepen
    url: http://codepen.io/
  - title: github
    url: https://github.com/
  - title: linkedin
    url: https://www.linkedin.com/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
